server:
  port: 19096

spring:
  application:
    name: payment-service
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/msa_exam
    username: root
    password: password
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
#  data:
#    redis:
#      host: localhost
#      port: 6379
#      password: systempass
#      username: default
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

messaging:
  exchanges:
    default: msa.exam
    error: msa.exam.error
  queues:
    order: msa.exam.order
    orderError: msa.exam.error.order


eureka:
  client:
    service-url:
      defaultZone: http://localhost:19090/eureka/

#management:
#  zipkin:
#    tracing:
#      endpoint: "http://localhost:9411/api/v2/spans"
#  tracing:
#    sampling:
#      probability: 1.0